import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Banner from './components/Banner/Banner'
import FrontEnd from './components/FrontEnd/FrontEnd'
import Menu from './components/Menu/Menu'
import Videos from './components/Videos/Videos'
import AboutMe from './components/AboutMe/AboutMe'
import Footer from './components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Menu />
        <Banner />

        <FrontEnd />
        <Videos />
        <AboutMe />

        <Footer />
      </main>
    </>
  )
}
